name: Run Checks

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Get Pull Request Number
        run: echo "PULL_NUMBER=$(echo "$GITHUB_REF" | awk -F / '{print $3}')" >> $GITHUB_ENV
        shell: bash

      - name: Check if another PR is open in the same repo
        run: |
          python .github/workflows/check-open-pr.py ${{ env.PULL_NUMBER }}

      - name: Check if a PR for the same folder is open in Buffer repo 
        run: |
          python .github/workflows/check-buffer-pr.py

      - name: Run Validator/Generator Raise a PR in Buffer repo
        run: |
          bash .github/workflows/raise-buffer-pr.sh ${{ env.PULL_NUMBER }}
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
